version: "3.8"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      - BACKEND_STORE_URI=sqlite:///mlflow.db
      - ARTIFACT_ROOT=/mlflow/artifacts
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "mlflow.server:app"]
    volumes:
      - mlflow-data:/mlflow
      - ./mlflow:/mlflow/artifacts
    restart: always

  api:
    build: .
    container_name: api_model
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - .:/app  # Monte le répertoire actuel du projet dans le conteneur sous /app
    working_dir: /app 
    restart: always

volumes:
  mlflow-data: 
